### ISSUE TITLE
Lazy loaded plugin won't sort with count motion, like a `3gs` keymap

### ISSUE THREAD

**Issue by wassimk** [sQVe/sort.nvim#4]
Here is how I have it setup in [lazy.nvim](https://github.com/folke/lazy.nvim):

``` ruby
    {
      'sQVe/sort.nvim',
      config = true,
      cmd = 'Sort',
      keys = {
        { 'gs', '<cmd>Sort<cr>', mode = 'n' },
        { 'gs', '<esc><cmd>Sort<cr>', mode = 'x' },
      },
    },
```

### Reproduce

Use these lines in Vim:

``` text
|b
a
c
```

### Expected Behavior

When I hit `3gs` I expect them to sort:

``` test
|a
b
c
```

I thought it might be an issue in _lazy.nvim_ but the author tried it, too without any luck. https://github.com/folke/lazy.nvim/issues/641. Any thoughts?

**Comment by sQVe** [comment]
Hey 👋,

This plugin does not support motions like that, since it's basically requiring the use of a visual selection. You can note this if you give the recommended key bindings a glance.

Adding the feature you're after is in the roadmap but it's likely not something I will get at in the near future. Any help with it is more than welcomed though.

Closing. Feel free to ping if you have any more questions.

**Comment by sQVe** [comment]
Also, see #3 for more context on the issue.

**Comment by sQVe** [comment]
> After the plugin loads, it works, which throws me off.

More than understandable 😅

The reason is that `sort.nvim` utilizes the built-in `sort` when possible, which supports motions like that.

**Comment by folke** [comment]
@wassimk I thought you would at least have verified that that was actually functionality of this plugin. 

Next time, please debug yourself before posting an issue. You're just wasting my time.

**Comment by wassimk** [comment]
> Next time, please debug yourself before posting an issue. You're just wasting my time

@folke I did try for quite a while. Obviously I didn’t understand. So sorry.
